import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href="/" className="text-blue-600 hover:text-blue-800 px-4 py-2">
          Home
        </Link>
        <Link
          href="/straight-line"
          className="text-blue-600 hover:text-blue-800 px-4 py-2"
        >
          Straight Line Depreciation
        </Link>
        <Link
          href="/about"
          className="text-blue-600 hover:text-blue-800 px-4 py-2"
        >
          About Us
        </Link>
        <Link
          href="/contact"
          className="text-blue-600 hover:text-blue-800 px-4 py-2"
        >
          Contact Us
        </Link>
        {children}
      </body>
    </html>
  );
}
